version: '3.1'

services:
  db:
    image: mysql:5.7.12
    container_name: meidrik-mysql
    environment:
      MYSQL_DATABASE: meidrik
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: meidrikuser
      MYSQL_PASSWORD: meidrikpw
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET collation_connection = utf8_unicode_ci;'
    ports:
      - 3309:3306
